apiVersion: v1 
kind: Pod
spec:
  containers:
  - name: gradle
    image: gradle:6.3-jdk14
    command:
    - sleep
    args:
    - 99d
    resources:
      limits:
        cpu: 500m
        memory: 1000M
      requests:
        cpu: 100m
        memory: 512M