apiVersion: v1 
kind: Pod
metadata:
  namespace: default
  labels:
    app: calc
spec:
  containers:
  - name: gradle
    image: gradle:jdk8
    command:
    - sleep
    args:
    - 99d
    resources:
      limits:
        cpu: 500m
        memory: 1000M
      requests:
        cpu: 100m
        memory: 512M
---
apiVersion: v1
kind: Service
metadata:
  name: calc-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: calc
  ports:
  - port: 8080