apiVersion: v1
kind: PersistentVolume
metadata:
  name: week8-pv
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/week8"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: week8-pv
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
