apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-deployment
  namespace: default
  labels:
    app: calc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calculator
        image: dlambrig/week8:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: calc-svc
  namespace: default
spec:
  type: NodePort
  selector:
    app: calc
  ports:
  - port: 8080

